name: "flutter_application_1"
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.4
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.2  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    #- assets/audio/meditation.mp3

flutter_native_splash:
  color: "#F9F5F9"
  image: assets/logo.png
  android: true
  ios: true
  fullscreen: true